# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vin.proto

require 'google/protobuf'

require 'google/protobuf/struct_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("vin.proto", :syntax => :proto3) do
    add_message "decodevin.VinRequest" do
      optional :vinnumber, :string, 1
    end
    add_message "decodevin.VinReply" do
      optional :results, :message, 1, "google.protobuf.Struct"
    end
  end
end

module Decodevin
  VinRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("decodevin.VinRequest").msgclass
  VinReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("decodevin.VinReply").msgclass
end
