# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: vin.proto for package 'decodevin'

require 'grpc'
require 'vin_pb'

module Decodevin
  module Vin
    # service definition
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'decodevin.Vin'

      # Decodes a VIN number
      rpc :DecodeVin, ::Decodevin::VinRequest, ::Decodevin::VinReply
    end

    Stub = Service.rpc_stub_class
  end
end
